### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by artalat** [BlueBaseJS/plugin-console-logger#6]
We need to release this plugin.

**Comment by abubakarmani1** [comment]
plugins is released

**Comment by artalat** [comment]
Doesn't seem to exist on npm

**Comment by abubakarmani1** [comment]
> Doesn't seem to exist on npm

Please watch the package is published and the Code pushed to master branch. @artalat please close the issue once verified

**Comment by artalat** [comment]
Still nothing: https://www.npmjs.com/search?q=%40bluebase%2Fplugin-console-logger

@danial24 can you resolve this

**Comment by artalat** [comment]
@ammarkhan967 when can we close this?
